# Objetivo do projeto e contexto (prever preços de carros para a empresa Cars 4 You).

# Import Libraries

In [58]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

# Create Meta Data

**carID:** An atribute that contains an identifier for each car.

**Brand:** The cars main brand (e.g., Ford, Toyota).

**model:** The car model.

**year:** The year of registration of the car.

**mileage:** The total reported distance travelled by the car (in miles).

**tax:** The amount of road tax (in £) that, in 2020, was applicable to the car in question.

**fuelType:** Type of Fuel used by car (Diesel, Petrol, Hybrid, Electric).

**mpg:** Average Miles per Gallon.

**engineSize:** Size of Engine in liters (Cubic Decimeters).

**paintQuality%** The mechanic’s assessment of the cars’ overall paint quality and hull integrity (filled by the mechanic during evaluation). 

**previousOwner:** Number of previous registered owners of the vehicle.

**hasDamage:** Boolean marker filled by the seller at the time of registration stating whether the car is damaged or not.

**price:** The car's price when purchased by Cars 4 You (in £).

# Import Dataset

In [59]:
import os
os.listdir('../data')

['test.csv', '.gitkeep', 'train.csv', 'sample_submission.csv']

In [60]:
sample = pd.read_csv('../data/sample_submission.csv')
train = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')

# EDA (Exploratory Data Analysis)

## Define new index for our datasets

In [61]:
sample.set_index('carID', inplace = True)
train.set_index('carID', inplace = True)
test.set_index('carID', inplace = True)

## Sample

In [62]:
print("Initial Analysis of the Sample Submission Dataset")
print('')
print(sample.shape)
print('-----------------------')
print(sample.head())
print('-----------------------')
print(sample.tail())

Initial Analysis of the Sample Submission Dataset

(32567, 1)
-----------------------
         price
carID
89856   851000
106581  514000
80886   323000
100174  921000
81376   620000
-----------------------
         price
carID
105775  412000
81363   441000
76833   684000
91768   835000
99627     2000

In [63]:
print("Continue to analyse the Sample Submission Dataset")
print('------------------------')
print('')
print(sample.info()) #From this output we can see that this dataset hasn't missing values
print('')
print('------------------------')
print(sample.describe())

Continue to analyse the Sample Submission Dataset
------------------------

<class 'pandas.core.frame.DataFrame'>
Index: 32567 entries, 89856 to 99627
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   price   32567 non-null  int64
dtypes: int64(1)
memory usage: 508.9 KB
None

------------------------
               price
count   32567.000000
mean   498198.943716
std    288111.809635
min      1000.000000
25%    249000.000000
50%    501000.000000
75%    746000.000000
max    999000.000000

## Train

In [64]:
train.shape

(75973, 13)

In [65]:
train.head()

,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
carID,,,,,,,,,,,,,
69512,VW,Golf,2016.0,22290,Semi-Auto,28421.0,Petrol,NaN,11.417268,2.0,63.0,4.000000,0.0
53000,Toyota,Yaris,2019.0,13790,Manual,4589.0,Petrol,145.0,47.900000,1.5,50.0,1.000000,0.0
6366,Audi,Q2,2019.0,24990,Semi-Auto,3624.0,Petrol,145.0,40.900000,1.5,56.0,4.000000,0.0
29021,Ford,FIESTA,2018.0,12500,anual,9102.0,Petrol,145.0,65.700000,1.0,50.0,-2.340306,0.0
10062,BMW,2 Series,2019.0,22995,Manual,1000.0,Petrol,145.0,42.800000,1.5,97.0,3.000000,0.0

In [66]:
train.tail()

,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
carID,,,,,,,,,,,,,
37194,Mercedes,C Class,2015.0,13498,Manual,14480.0,etrol,125.0,53.3,2.0,78.0,0.0,0.0
6265,Audi,Q3,2013.0,12495,Semi-Auto,52134.0,Diesel,200.0,47.9,2.0,38.0,2.0,0.0
54886,Toyota,Aygo,2017.0,8399,Automatic,11304.0,Petrol,145.0,67.0,1.0,57.0,3.0,0.0
860,Audi,Q3,2015.0,12990,Manual,69072.0,iesel,125.0,60.1,2.0,74.0,2.0,0.0
15795,Ford,Fiesta,2018.0,10495,Manual,16709.0,Petro,145.0,64.2,1.1,38.0,1.0,0.0

From the visualization of the head and tail of the data base we can already understand that some errors exist:

    - Missing values
    - Values that should be integers as floats (2020.0)
We will further analyse this using describe and info.

It's also possible to see that some strings have the same information written in different forms (Diesel, iesel; Mercedes, mercedes).
To solve this problem we will uniformize all the values in data preparation

In [67]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75973 entries, 69512 to 15795
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           74452 non-null  object
 1   model           74456 non-null  object
 2   year            74482 non-null  float64
 3   price           75973 non-null  int64
 4   transmission    74451 non-null  object
 5   mileage         74510 non-null  float64
 6   fuelType        74462 non-null  object
 7   tax             68069 non-null  float64
 8   mpg             68047 non-null  float64
 9   engineSize      74457 non-null  float64
 10  paintQuality%   74449 non-null  float64
 11  previousOwners  74423 non-null  float64
 12  hasDamage       74425 non-null  float64
dtypes: float64(8), int64(1), object(4)
memory usage: 8.1+ MB

From info we can see that:

    - year as a float...
    - previousOwners, hasDamage also as floats but they should be integers and booleans respectively
    - Missing values in all features except the price 

What will we do?

    Analyse with describe to have a different view

In [68]:
train.describe()

,year,price,mileage,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
count,74482.000000,75973.000000,74510.000000,68069.000000,68047.000000,74457.000000,74449.000000,74423.000000,74425.0
mean,2017.096611,16881.889553,23004.184088,120.329078,55.152666,1.660136,64.590667,1.994580,0.0
std,2.208704,9736.926322,22129.788366,65.521176,16.497837,0.573462,21.021065,1.472981,0.0
min,1970.000000,450.000000,-58540.574478,-91.121630,-43.421768,-0.103493,1.638913,-2.345650,0.0
25%,2016.000000,10200.000000,7423.250000,125.000000,46.300000,1.200000,47.000000,1.000000,0.0
50%,2017.000000,14699.000000,17300.000000,145.000000,54.300000,1.600000,65.000000,2.000000,0.0
75%,2019.000000,20950.000000,32427.500000,145.000000,62.800000,2.000000,82.000000,3.000000,0.0
max,2024.121759,159999.000000,323000.000000,580.000000,470.800000,6.600000,125.594308,6.258371,0.0

From the numeric describe we can see that we have some weird values:

    1. negative mileage, tax, mpg, engineSize, previousOwners in the minimum value
    2. hasDamage is a boolean but we can see that instead of 0 and 1 we only have 0 and Nones*
    3. previousOwner has a float? Should we round it?

*check in the hasDamage column

What will we do:

    1. Count the number of negative values and decide if we should drop or change them.
    2. Replace the nones by 1's. (data-preparation)
    3. Count the number of float values and decide to drop or round them.

In [69]:
train.describe(include='object')

        Brand   model transmission fuelType
count   74452   74456        74451    74462
unique     72     735           40       34
top      Ford   Focus       Manual   Petrol
freq    14808    6353        38050    37995

From the categorical describe we can confirm that this columns also have missing values

In [73]:
for column in train.columns:
    unique_values = train[column].unique()
    print(f"Unique values on the column '{column}': {unique_values}")
    print('-----------------------------------')
    print('')

Unique values on the column 'Brand': ['VW' 'Toyota' 'Audi' 'Ford' 'BMW' 'Skoda' 'Opel' 'Mercedes' 'FOR'
 'mercedes' 'Hyundai' 'w' 'ord' 'MW' 'bmw' nan 'yundai' 'BM' 'Toyot' 'udi'
 'Ope' 'AUDI' 'V' 'opel' 'pel' 'For' 'pe' 'Mercede' 'audi' 'MERCEDES'
 'OPEL' 'koda' 'FORD' 'Hyunda' 'W' 'Aud' 'vw' 'hyundai' 'skoda' 'ford'
 'TOYOTA' 'ercedes' 'oyota' 'toyota' 'SKODA' 'Skod' 'HYUNDAI' 'kod' 'v'
 'for' 'SKOD' 'aud' 'KODA' 'PEL' 'yunda' 'or' 'UDI' 'OYOTA' 'HYUNDA' 'mw'
 'OPE' 'mercede' 'ERCEDES' 'ercede' 'TOYOT' 'MERCEDE' 'ORD' 'ud' 'ope'
 'AUD' 'hyunda' 'skod' 'toyot']
-----------------------------------

Unique values on the column 'model': [' Golf' ' Yaris' ' Q2' ' FIESTA' ' 2 Series' '3 Series' ' A3' ' Octavia'
 ' Passat' ' Focus' ' Insignia' ' A Clas' ' Q3' ' Fabia' ' A Class' ' Ka+'
 ' 3 Series' ' GLC Class' ' I30' ' C Class' ' Polo' ' E Class' ' C Clas'
 ' Q5' ' Up' ' Fiesta' ' C-HR' ' Mokka X' ' Corsa' ' Astra' ' TT'
 ' 5 Series' ' Aygo' ' 4 Series' ' SLK' ' Viva' ' T-Roc' 'Focus'
 ' EcoSport' ' Tucson' ' EcoSpor' nan ' X-CLASS' ' CL Class' ' IX20'
 ' i20' ' Rapid' ' a1' ' Auris' ' sharan' ' I20' ' Adam' ' X3' ' A8'
 ' GLS Class' ' B-MAX' ' A4' ' Kona' ' I10' ' A1' ' Mokka' ' fiesta'
 ' S-MAX' ' X2' ' Crossland X' ' Tiguan' ' A5' ' GLE Class' ' C CLASS'
 ' mokka x' ' Zafira' ' Ioniq' ' A6' ' Mondeo' ' Yeti Outdoor' ' X1'
 'POLO' ' INSIGNIA' ' Scala' ' S Class' ' 1 Series' ' Kamiq' ' Kuga'
 ' Tourneo Connect' ' Q7' ' GLA Class' ' Arteon' ' polo' ' SL CLASS'
 'Tucson' ' Santa Fe' ' Grandland X' ' I800' ' ASTRA' ' RAV4' ' c class'
 ' Touran' ' Citigo' ' Focu' ' Roomster' ' Prius' ' Corolla' ' Fiest'
 ' B Class' ' Sharan' ' Q' ' Kodiaq' ' V Class' ' POLO' ' GOLF' ' E Clas'
 ' Caddy Maxi Life' ' SUPERB' ' Astr' ' Getz' 'T-Roc' ' YARIS'
 ' Combo Life' ' FOCUS' ' Beetle' ' E CLASS' ' PRIUS' 'Fabia' ' Galaxy'
 ' M3' ' GTC' ' 2 series' '1 Series' ' 1 SERIES' ' X4' 'Golf' 'Auris'
 ' KA' ' IX35' ' 3 Serie' 'E Class' ' Grand Tourneo Connect' ' Shara'
 ' M4' ' 3 series' ' Tourneo Custom' 'Touran' ' Superb' ' focus'
 '5 Series' ' Z4' ' 2 serie' ' X5' ' Meriva' ' Octavi' ' yeti outdoor'
 ' Kug' ' RS6' ' Verso' ' Touareg' ' MONDEO' ' Shuttle' ' CLS Class'
 ' C-MAX' ' Mokka ' ' Puma' ' CLA Class' ' I40' ' q3' ' x1' 'X5'
 ' Tiguan Allspace' ' 6 Series' ' Caravelle' ' crossland x' ' 4 SERIES'
 ' Karoq' ' a5' ' I3' 'A4' ' Mokk' 'Ka+' ' Grand C-MAX' ' Pol'
 ' GRAND C-MAX' ' T-Cross' ' 4 Serie' 'Astra' 'Q3' ' viva' ' 4 serie'
 ' A7' ' GLE Clas' ' Golf SV' 'A Class' ' A' ' 1 Serie' ' KUGA' ' Gol'
 ' Agila' ' AURIS' ' Ayg' ' GT86' 'C Class' ' astra' ' corsa' ' Yeti'
 ' California' '4 series' ' X' 'A5' 'Touareg' ' Land Cruiser' ' MOKKA X'
 ' a4' ' EDGE' ' i10' ' 5 Serie' ' X6' 'Toura' 'Karoq' ' Caddy Life'
 ' rav4' ' 8 Series' 'GLC Class' 'Polo' ' Fusion' ' GL Class' ' Scirocco'
 ' TOURAN' ' kuga' ' Z3' ' SL CLAS' ' fabia' ' Kodia' 'ASTRA' ' tiguan'
 '2 Series' ' PROACE VERSO' ' hilux' ' Passa' ' Hilux' 'GLA Class'
 ' Amarok' ' FABIA' ' Edge' 'CLA Class' ' CC' ' x5' ' Insigni' ' 7 Series'
 'Q5' ' Avensis' ' 5 SERIES' 'Meriva' ' Eos' ' M Class' 'Yaris' ' VERSO'
 'A1' ' Grandland ' 'Mondeo' 'Corsa' ' Zafira Tourer' ' ECOSPORT' ' RS5'
 'Tiguan' 'A3' ' TUCSON' ' R8' ' b class' '4 Series' ' Mustang' ' V Clas'
 ' 5 series' 'GLE Class' ' Tigua' ' I1' ' cl class' ' B-MA' 'Grandland X'
 'Viva' 'Kuga' ' Antara' ' Q8' ' Ka' ' T-RO' ' Camry' ' FOCU'
 ' YETI OUTDOOR' ' 1 series' ' Rapi' ' auris' 'Fiesta' 'RAV4' ' CLK'
 'Mokka X' ' mondeo' ' RS3' ' a3' ' a class' ' Jetta' ' e class'
 ' 3 SERIES' 'focus' 'Golf SV' ' m class' ' i3' ' golf' ' Kadjar' ' Cors'
 ' Zafira Toure' ' q5' ' GLC CLASS' 'U' ' PASSAT' ' MERIVA' 'A6' ' Yari'
 ' SQ5' ' slk' ' B Clas' ' KAMIQ' ' aygo' 'Mokka' 'Prius' ' passat'
 ' A CLASS' ' VIVA' ' rapid' ' mokka ' ' insignia' ' mokka' ' Citig'
 ' S-MA' ' RS4' ' puma' ' ayg' ' Supra' ' x2' ' AYGO' ' 4 series' 'golf'
 ' GALAXY' ' Tucso' ' i8' ' X7' ' Galax' ' t-roc' ' Super' ' sq7'
 ' G Class' ' i30' ' C-H' ' 2 SERIES' ' GLA CLASS' ' KONA' ' OCTAVIA'
 ' x-clas' ' x3' 'I10' ' grandland x' ' GLC Clas' ' S3' 'Insignia' 'Focu'
 ' COMBO LIFE' 'I40' ' I80' ' tt' 'Zafira' ' Crossland ' 'B-MAX'
 ' 2 Serie' ' Arteo' ' Tigra' ' CORSA' ' Escort' ' GLB Class' ' 3 serie'
 ' c-hr' ' SCALA' ' MONDE' ' yaris' ' GLA Clas' ' CL Clas' ' Vivaro'
 ' Verso-S' 'gtc' ' Monde' ' corolla' ' 7 Serie' ' T-Ro' ' up' ' X-CLAS'
 'Adam' ' gla class' ' TOUAREG' ' Ioni' ' T-Cros' 'Passat' ' gle class'
 ' Viv' ' M5' '2 Serie' ' kodiaq' ' x-class' ' Veloste' 'Superb'
 ' Santa F' 'Aygo' ' Zafir' 'Octavia' 'C-MAX' ' S4' ' T-ROC' ' UP'
 ' citigo' ' Yeti Outdoo' ' edge' ' Auri' ' santa fe' ' mustang' 'Citigo'
 ' q7' ' Fabi' ' q2' ' IQ' ' glc class' 'RAV' ' A2' ' gt86' ' CL CLASS'
 ' yeti' 'Hilux' ' TIGUAN' ' Caddy Maxi' '200' 'SL CLASS' ' CITIGO'
 ' amarok' 'Up' ' verso' ' scirocco' 'Ioniq' 'Q8' ' U' 'Arteon' ' superb'
 'Q7' ' T-CROSS' ' KA+' ' Streetka' ' Roomste' ' ZAFIRA' ' ecosport'
 'Scala' ' v class' ' ka+' ' x' ' KAMI' ' c-max' ' karoq' ' Caddy' 'polo'
 'Z4' 'B Class' ' galaxy' ' octavia' ' TIGUAN ALLSPACE' ' KAROQ' ' ka'
 ' caravelle' ' Cascada' 'GTC' ' scala' ' s-max' 'C-HR' 'kodiaq' 'B-MA'
 ' C-MA' ' Accent' 'CLS Class' ' tourneo custom' ' cls class' ' touareg'
 ' KODIAQ' 'TT' ' Karo' ' 6 SERIES' ' b-max' ' SCIROCCO' ' shuttle' ' Kon'
 'Octavi' ' tourneo connect' ' Scirocc' ' a6' 'S Class' ' PUMA'
 ' grand c-max' ' S8' ' RS' ' touran' 'Q2' 'C Clas' 'Kona' ' a' 'X2'
 ' CROSSLAND X' ' gol' ' tiguan allspace' ' Golf S' ' RAV' ' K' ' S Clas'
 ' SANTA FE' ' Grand C-MA' ' Toura' 'E CLASS' 'S-MAX' 'M3' ' Beetl' 'rav4'
 'I20' ' COROLLA' ' s3' ' zafira' 'Mustang' ' V CLASS' 'x1' ' a7'
 'Santa Fe' 'EcoSport' ' tucson' 'Beetle' ' TIGUA' ' Ada' ' INSIGNI'
 ' grandland ' ' adam' 'SLK' ' Z' ' CLS Clas' 'Amarok' ' s class'
 'a class' ' SQ7' ' AVENSIS' ' Ranger' 'Crossland X' 'fiesta' 'X6' 'Fiest'
 ' golf s' ' golf sv' ' I2' 'Scirocco' ' MOKKA' ' Grand Tourneo Connec'
 ' M' 'RS6' ' S CLASS' ' Meriv' 'Zafir' ' Caravell' 'Pol' ' C CLAS' ' cc'
 'Verso' '220' ' super' 'A8' ' VECTRA' ' combo life' '5 SERIES' ' B CLASS'
 ' CLS CLASS' ' KON' ' Tiguan Allspac' ' IONIQ' ' CLA CLASS' 'Sharan'
 ' ix20' 'Insigni' 'Tourneo Connect' ' Scal' ' 6 series' ' 8 Serie' '230'
 'UP' 'Galaxy' ' scal' ' Ampera' 'T-Cross' 'FIESTA' ' Fox' 'Fusion'
 ' Urban Cruiser' 'astra' 'b class' 'a8' ' GLS Clas' ' ADAM' ' avensis'
 ' Amaro' 'I30' 'Arteo' ' M2' ' T' ' M CLASS' ' kona' 'M Class' 'IONIQ'
 'Tigua' '6 Series' ' Coroll' '1 SERIES' ' 1 SERIE' ' Combo Lif' 'Golf S'
 'Roomster' ' cors' ' GL CLASS' 'CC' 'X1' ' Caddy Maxi Lif' 'aygo' ' yari'
 'X7' 'X3' ' prius' ' kamiq' ' TUCSO' ' M Clas' 'Z3' 'Supra' ' t-cros'
 'Yari' ' sl class' ' Touare' ' i40' 'CL Class' ' YARI' ' GOL' ' meriva'
 'Yeti Outdoor' ' CORS' 'c class' 'A CLASS' ' GLS CLASS' 'TIGUAN' ' S5'
 'COMBO LIFE' ' Tourneo Custo' ' a clas' 'corsa' 'e class' ' Edg' 'Tucso'
 ' 7 SERIES' 'A7' ' Yet' 'i3' ' IX2' 'FABIA' ' c clas' '1 series' ' focu'
 ' 1 serie' ' TOURA' 'Corolla' ' SL' ' i' 'Vectra' ' 7 series' 'q5'
 ' CLC Class' ' GOLF SV' 'KA' 'tiguan' ' M6' 'CLK' ' gtc' ' SHARAN' 'Gol'
 ' Hilu' ' GLE CLASS' 'M5' ' gls class' 'Mokka ' '3 Serie' ' glc clas'
 ' ix35' 'IX35' 'V Class' ' Urban Cruise' 'Rapid' 'Combo Life' ' z4'
 ' ioniq' ' GRANDLAND X' ' t-cross' 'corolla' 'R8' 'Mokk' 'octavia'
 ' 6 Serie' ' JETTA' ' Land Cruise' 'ka+' ' rav' 'Grand C-MAX' ' 8 series'
 'RS3' 'kuga' ' cla class' ' ARTEON' ' r8' ' beetle' ' gl class' 'Yeti'
 'GL Class' 'IX20' ' Vectra' ' 8 SERIES' ' Vers' ' Terracan'
 ' ZAFIRA TOURER' 'Kodiaq' 'Zafira Tourer' ' m3' ' AYG' 'Avensis' ' s-ma'
 'X4' ' m4' 'yaris' 'FOCUS' ' arteon' ' glb class']
-----------------------------------

Unique values on the column 'year': [2016.         2019.         2018.         2014.         2017.
 2020.         2013.                   nan 2015.         2023.36707842
 2011.         2012.         2023.1169636  2003.         2009.
 2007.         2005.         2011.11118842 2011.21085349 2023.97731126
 2004.         2010.         2010.56500919 2008.         2024.12175905
 2006.         2023.60527574 2023.38982198 2010.67696784 2001.
 2000.         2023.26798867 2010.26863473 2010.37154646 2002.
 2022.69668507 2009.81675711 2010.7464032  2012.69574039 1996.
 1998.         2022.87800554 1970.         1999.         1997.        ]
-----------------------------------

Unique values on the column 'price': [22290 13790 24990 ... 33606 16809 25785]
-----------------------------------

Unique values on the column 'transmission': ['Semi-Auto' 'Manual' 'anual' 'Semi-Aut' 'Automatic' 'manual' nan
 'unknown' 'Manua' 'AUTOMATIC' 'MANUAL' 'semi-auto' ' Manual ' 'automatic'
 'emi-Auto' 'SEMI-AUTO' 'SEMI-AUT' 'Automati' 'ANUAL' 'utomatic' 'unknow'
 'EMI-AUTO' 'manua' 'anua' 'emi-Aut' 'MANUA' 'emi-auto' 'UTOMATIC'
 ' manual ' ' MANUAL ' 'UNKNOWN' 'nknown' 'automati' 'Other' 'semi-aut'
 ' Manual' 'AUTOMATI' 'utomati' 'Manual ' 'manual ' 'nknow']
-----------------------------------

Unique values on the column 'mileage': [28421.  4589.  3624. ... 13613. 52134. 69072.]
-----------------------------------

Unique values on the column 'fuelType': ['Petrol' 'Diesel' 'etrol' 'Hybrid' 'diesel' 'iesel' nan 'petrol' 'PETROL'
 'Diese' 'Petro' 'DIESEL' 'petro' 'HYBRID' 'ybri' 'Other' 'DIESE' 'Hybri'
 'ETROL' 'ybrid' 'PETRO' 'hybrid' 'IESEL' 'Electric' 'ther' 'iese' 'etro'
 'ETRO' 'diese' 'Othe' 'YBRID' 'HYBRI' 'OTHER' 'other' 'IESE']
-----------------------------------

Unique values on the column 'tax': [         nan 145.          30.          20.         150.
 160.         -56.19320154   0.         125.         200.
 250.         135.         300.         205.         260.
 326.02823317 325.         -45.78061049 265.         305.
 303.14889146 235.         299.47350391 240.         165.
 140.         540.         155.         220.         120.
 330.         290.48678508 -20.24107949 -18.33074314 327.91577835
 270.         115.         185.         316.48718937 570.
 -49.15354066 316.29630636 -60.6840948  555.         277.38425448
 -91.12163048  10.         315.         190.         -31.91494466
 230.         -43.24208237 294.84340933 195.         580.
 290.         130.         565.         210.         280.
 255.         520.         295.         245.         110.
 535.        ]
-----------------------------------

Unique values on the column 'mpg': [ 11.41726775  47.9         40.9         65.7         42.8
  60.1         68.9         62.8         67.3         54.3
  57.7                 nan  56.5         72.4         47.1
  44.1         46.3         32.5         48.7         74.3
  43.5         78.5         51.4         50.4         67.
  28.5         64.2         61.4         41.5         52.3
  53.3         44.8         35.8         80.7         37.2
  49.6         42.2         45.6         34.          74.4
  29.1         76.3         40.3         58.9         39.8
  55.4         40.4         78.4         83.1         33.2
  34.5         70.6         35.3         39.2         32.8
  34.9         61.7         30.         156.9         36.2
  58.          38.2         69.          37.7         57.6
  66.         151.04180955   9.42917895  85.6         58.8
  89.77369267  78.          30.4         36.7        235.
 134.5         27.70948954  88.32163955  88.3         56.6
 -43.42176751 100.99894302  31.          38.7         33.6
  20.74549979  22.1        188.3         47.7         43.4
  31.4         28.8         76.4         24.6         68.8
  55.          29.4         94.1         20.71009481  31.7
  32.1         32.9         30.1         22.4         53.
  28.          94.78638042   5.5          6.          30.7
  47.          27.2          1.1         43.          65.6
  29.7         21.4          9.82146197  86.          29.5
  23.5         26.4        113.          55.5         81.56893961
  16.3501525  117.7         43.6        166.          92.82689954
  22.6         24.8         26.9         33.7        470.8
 256.8         54.4        166.2          8.8        217.3
  25.5         23.          21.6        110.34497687 148.7
  25.4         22.2        141.2         38.1         27.4
  23.7        122.8         61.1         22.8         20.9
  44.6         92.11045521  34.4         23.3         42.4
  27.7         78.6         28.3         14.49714632  20.8
  23.9        201.8        176.6         21.1         24.1
  42.1         25.2         19.5        141.3         19.6
  46.          38.6          2.8         40.          30.8
  28.2         51.3         51.1         22.3         42.9
  24.4         17.8        122.9        135.5         26.7
  33.3         21.9         62.7         20.5        235.4
  42.          37.6         19.8         26.6         42.16
  19.          20.3         21.7         54.2         25.9
  26.3        128.4         20.          19.1        100.9
  48.4         21.          26.2         19.3         54.7
  27.9         67.7         53.5       ]
-----------------------------------

Unique values on the column 'engineSize': [ 2.          1.5         1.          1.4         1.6                nan
  1.2         3.          1.8         2.1         1.3         0.7395339
  0.          2.3         1.1         4.          1.7         2.98579344
  2.2         2.5         2.61964142 -0.1034928   2.78177621  2.63120047
  3.72371217  0.15452932  4.2         3.2         2.9         2.8
  0.31340658  2.06411863  3.73923548  2.4         0.18642488  2.6631132
  5.2         0.19146242  5.          0.30707394  0.37112737  4.4
  6.2         3.82275785  1.9         0.6         6.6         5.5
  3.5         4.7         0.16286595  2.7         3.6         2.6
  4.3         5.4         4.5         4.1         6.        ]
-----------------------------------

Unique values on the column 'paintQuality%': [ 63.          50.          56.          97.          74.
  75.          59.          85.          35.          68.
  45.          30.          69.          53.          57.
  40.          60.          94.          33.          51.
  47.          87.          61.          83.          95.
  46.          54.          80.          77.          90.
  91.          71.          44.          38.          64.
  55.          66.          82.          41.          81.
  79.          72.          34.          88.                  nan
  43.          31.          32.          96.          84.
  70.          86.          92.          52.          39.
  42.          73.          78.          37.          65.
  93.          89.          99.          36.          62.
 125.10995148   3.1152953   67.         125.5694986   76.
  48.           3.17268306  49.           3.25476013 125.59430832
  98.          58.           3.20741784 125.4535988    3.14037046
   1.76947364   3.22574362 125.30194543 125.20203342 125.18872876
 125.36650692   2.72515272 125.00377307   1.63891309]
-----------------------------------

Unique values on the column 'previousOwners': [ 4.          1.         -2.34030622  3.          0.          2.
         nan -2.34565     6.25837066 -2.33512284  6.22789796  6.25823052
  6.23017958 -2.33936045  6.21772443  6.24583495 -2.29943868 -2.34010209
 -2.31225953  6.2482512  -2.31733109  6.23308217  6.24177863 -2.33744529]
-----------------------------------

Unique values on the column 'hasDamage': [ 0. nan]
-----------------------------------

Comments on the results above for each feature:
- Brand have significant inconsistencies with case sensitivity, ('mercede', 'FOR'), and fragmented entries ('pel', 'udi').

- Model have a lot of variations due to leading/trailing spaces, inconsistent casing, typos ('Focu' instead of 'Focus'), and incomplete entries ('A Clas').

- Year have decimal/fractional values (e.g., 2023.36707842) suggests data encoding errors or floating-point artifacts. 

- Price have numeric and diverse.

- Transmission column with multiple variants and typos exist for common types (e.g., 'Manual', 'manua', 'anual'). 

- Mileage appears mostly clean and numeric.

- FuelType have many spelling and case variations (e.g., 'Petrol', 'petrol', 'etrol') exist.

- Tax with negative and fractional values are suspicious, suggesting data errors or unusual cases. 

- MPG looks like contain outliers and invalid negative values.

- EngineSize is mostly numeric but includes some unusual fractional and zero values that should be verified.

- PaintQuality% looks like have some outliers and very small unusual values are present that can make no sense.

- PreviousOwners contains unexpected negative/fractional values and NaNs.

- HasDamage is Binary flag with values 0 and NaN.

### Check for duplicates

In [ ]:
train.duplicated().sum()
#We conclude that there aren't any duplicates on the whole table

Besides not having duplicates it's important to examine again the duplicates without the carID, to prevent redundancy.

In [ ]:
#First we create a copy of our dataFrame 
train_copy= train.copy()
train_copy.head()

In [ ]:
#We drop carID
train_without_ID = train_copy.drop('carID', axis=1)
train_without_ID.head() #to check that everything is okay

In [ ]:
train_without_ID.duplicated().sum() 
#count the total of duplicates of our new DataFrame

After this analysis we found inly 4 duplicates, we decide to drop the duplicate lines.

### GroupBy

In [ ]:
train.groupby('hasDamage')['price'].mean()

From the code before we can see that the price mean for the cars that have no damage is 16883.212509. 
It would also make sense to analyse the mean price of the cars with damage but the problem is that assume that we have cars with damage, because the column with the feature hasDamge has no 1's.
this way it's impossible to check the mean price of the cars with damage.

In [ ]:
train.groupby('mileage')['price'].mean()
#Here we can check a decrease of the price with the increase of the mileages
#But we still have the problem of the negatives mileages

In [ ]:
train.groupby('year')['price'].mean()
#It's possible to verify that the price varies depending ont he year of manufacture of the cars. 
#This is, the older the car, he cheaper it is

In [ ]:
!!!!! O CÓDIGO A SEGUIR FORAM RACIOCÍNEOS QUE FIZ QUE PODIAM DAR RESULTADOS GIROS MAS QUE NÃO SEI SE VALE A PENA POR  !!!!

train.groupby('previousOwners')['price'].mean()
#aqui podiamos relacionar o aumento do nº de donos com a diminuição do preço mas acho que os resultados não mostram nada muito
#interessante, não sei se vale a pena por

train.groupby('Brand')['price'].mean()
#pode ser interessante ver depois de ter corrigido o problema dos erros na escrita de cada marca. 
# é claro pelo resultado que por exemplo os yundais sao mais baratos que maior parte das outras marcas

train.groupby('paintQuality%')['price'].mean()
#acho que o resultado não mostra nada que tenha uma boa conclusao

In [ ]:
!!!!! O CÓDIGO A SEGUIR FORAM RACIOCÍNEOS QUE FIZ QUE PODIAM DAR RESULTADOS GIROS MAS QUE NÃO SEI SE VALE A PENA POR  !!!!

train.groupby('year')['paintQuality%'].mean()
#poderiamos ver que quanto mais velho o carro pior a qualidade de pintura, mas acho que isso não é muito explicito pelos resultados

train.groupby('previousOwners')['paintQuality%'].mean()
#os resultados tb nao permitem concluir nada

train.groupby('hasDamage')['paintQuality%'].mean()
#acho que aqui era giro comparar a qualidade de pintura com os carros que têm e não têm estragos mas como só temos missing values nos sitios dos 1's nao conseguimos concluir nada disso

### Define the independent variables as X and the dependent as Y

In [ ]:
X = train.drop('price', axis = 1)
y = train['price']

TO DO:
- corrigir types
- remover outliers graves, que são erros e visualizar boxplots
- Feature engineering: Criar features que não envolvem cálculos c/ média, mediana, …
Fazer tudo isto para o training and test set

### Split the dataset into train and validation

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size = 0.3, 
                                                  random_state = 0, 
                                                  #stratify = y- não pus esta parte como no notebook pq estava a dar erro e acho que é pq a nossa variavel y aqui não é um boolean mas sim um float
                                                  shuffle = True)

TO DO:

- Feature engineering: Criar features que envolvem cálculos c/ média, mediana, … (fazer para os 3 sets que temos)
- Preencher missing values nos 3 datasets, acho que dá para usar uma função ‘transform’ (justificar para depois por no report)  
!!!!!ATENÇÃO: os valores de média, moda,… a usar neste últimos dois passos são todos retirados apenas do training set e não do validation set

### Fill missing values

As we saw there are missing values in a couple of variables so we will fill the categories missing values with 'Unknow' and the numericals with the average.

But before do that we'll split our columns in metric and non_metric features.

In [ ]:
for column in ['Brand', 'model', 'transmission', 'fuelType']:
    X_train[column] = X_train[column].fillna('Unknown')
    X_val[column] = X_val[column].fillna('Unknown')

In [ ]:
for column in X_train.columns:
    if pd.api.types.is_numeric_dtype(X_train[column]):
        
        #store mean of training data in a variable - in a real application, you may need to store these values for future usages on e.g. test data 
        mean_to_fill = X_train[column].mean()
        
        #fill on X_train
        X_train[column].fillna(mean_to_fill, inplace=True)
        #Fill on X_val
        X_val[column].fillna(mean_to_fill, inplace=True)

## Test

In [ ]:
test.shape
#Here we can see that the test shape is equal to the sample shape.

(32567, 12)

In [ ]:
test.head(15)

,Brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
carID,,,,,,,,,,,,
89856,Hyundai,I30,2022.878006,Automatic,30700.000000,petrol,205.0,41.50000,1.6,61.0,3.0,0.0
106581,VW,Tiguan,2017.000000,Semi-Auto,-48190.655673,Petrol,150.0,38.20000,2.0,60.0,2.0,0.0
80886,BMW,2 Series,2016.000000,Automatic,36792.000000,Petrol,125.0,51.40000,1.5,94.0,2.0,0.0
100174,Opel,Grandland X,2019.000000,Manual,5533.000000,Petrol,145.0,44.10000,1.2,77.0,1.0,0.0
81376,BMW,1 Series,2019.000000,Semi-Auto,9058.000000,Diesel,150.0,51.40000,2.0,45.0,4.0,0.0
85391,Ford,Fiesta,2018.000000,Manual,29626.000000,Petrol,145.0,65.70000,1.0,64.0,1.0,0.0
82175,BMW,X1,2016.000000,Manual,57717.000000,Diese,125.0,58.90000,2.0,50.0,1.0,0.0
95250,Mercedes,B Class,2017.000000,Manual,14005.000000,Diesel,145.0,65.70000,NaN,64.0,4.0,0.0
85071,Ford,Focus,2011.000000,Manual,68274.000000,Petrol,145.0,47.90000,1.6,71.0,4.0,0.0
96210,Skoda,Superb,2019.000000,Manual,20632.000000,Diesel,145.0,64.20000,2.0,99.0,3.0,0.0
80317,BMW,5 Series,2019.000000,Semi-Auto,9131.000000,Diesel,145.0,62.80000,2.0,73.0,3.0,0.0
92731,Mercedes,C Class,2018.000000,unknow,20173.000000,Diesel,145.0,61.40000,2.1,78.0,0.0,NaN
107704,VW,Up,2018.000000,Automatic,2154.000000,Petrol,145.0,94.78638,1.0,40.0,0.0,0.0
98302,Toyot,Aygo,2017.000000,Manual,13255.000000,Petrol,145.0,69.00000,1.0,35.0,3.0,0.0
107055,VW,Golf,2017.000000,Semi-Auto,20168.000000,Petrol,200.0,39.80000,2.0,76.0,1.0,0.0

In [ ]:
test.tail(15)

,Brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
carID,,,,,,,,,,,,
90396,Hyundai,I10,2017.0,Manual,5970.00000,Petrol,150.0,60.1,1.0,75.0,0.0,0.0
97935,Toyota,Aygo,2019.0,Manual,10.00000,Petrol,145.0,56.5,1.0,89.0,2.0,0.0
80399,BMW,5 Series,2019.0,Automatic,1522.00000,Hybrid,135.0,141.3,2.0,38.0,3.0,0.0
105883,VW,Polo,2017.0,Manual,19812.00000,Petrol,145.0,60.1,1.2,71.0,1.0,0.0
92823,Mercedes,C Clas,2019.0,Semi-Auto,10545.00000,etrol,NaN,NaN,1.5,NaN,1.0,0.0
82238,BMW,i3,2017.0,AUTOMATIC,19178.00000,Other,0.0,470.8,0.6,43.0,0.0,0.0
98091,Toyota,Prius,2016.0,Automatic,28000.00000,hybrid,0.0,85.6,1.8,46.0,4.0,0.0
87257,Ford,Fiesta,2017.0,Semi-Auto,4512.00000,Petrol,0.0,57.7,1.0,35.0,0.0,0.0
87937,Ford,Fiesta,2018.0,Manual,10297.00000,Petrol,150.0,64.2,1.1,68.0,3.0,0.0
97548,Skoda,Octavia,2019.0,Semi-Auto,15118.00000,etrol,150.0,54.3,1.5,68.0,0.0,0.0
105775,VW,Tiguan,2017.0,Manual,27575.00000,Petrol,145.0,46.3,1.4,94.0,1.0,0.0
81363,BMW,X2,2020.0,Automatic,1980.00000,Petrol,145.0,34.0,2.0,39.0,3.0,0.0
76833,Audi,Q5,2019.0,Semi-Auto,8297.00000,Diesel,145.0,38.2,2.0,88.0,4.0,0.0
91768,Mercedes,A Class,2019.0,Manual,-50755.21023,Petrol,145.0,28.5,1.3,81.0,1.0,0.0
99627,Toyota,Yaris,2017.0,Automatic,11071.00000,Petrol,30.0,58.0,1.3,98.0,4.0,0.0

From the visualization of the head and tail of the data base we can already understand that some errors exist:

    - Missing values
    - Values in the columns Year, hasDamage, previousOwners that should be integers as floats (2020.0)
    - Floats on mpg, previousOwners column with diferent sizes
    - A category unknown in transmission column
    - It looks like the column hasDamage only contains 0's and blanks/None values, are the blanks supose to be 1's?
    - PreviousOwner and tax: negative values are impossible
We will further analyse this using describe and info.

It's also possible to see that some strings have the same information written in different forms (Petrol as etrol, Automatic and AUTOMATIC).
To solve this problem we will uniformize all the values in data preparation

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32567 entries, 89856 to 99627
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           31918 non-null  object
 1   model           31917 non-null  object
 2   year            31914 non-null  float64
 3   transmission    31944 non-null  object
 4   mileage         31878 non-null  float64
 5   fuelType        31911 non-null  object
 6   tax             29259 non-null  float64
 7   mpg             29279 non-null  float64
 8   engineSize      31939 non-null  float64
 9   paintQuality%   31942 non-null  float64
 10  previousOwners  31970 non-null  float64
 11  hasDamage       31970 non-null  float64
dtypes: float64(8), object(4)
memory usage: 3.2+ MB

From info we can see that:

    - year, as a float...
    - previousOwners, hasDamage also as floats but they should be integers and booleans respectively
    - Missing values in all features

What will we do?

    Analyse with describe to have a different view

In [ ]:
test.describe()

,year,mileage,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
count,31914.000000,31878.000000,29259.000000,29279.000000,31939.000000,31942.000000,31970.000000,31970.0
mean,2017.102299,22952.658921,120.569239,55.210728,1.665377,64.446667,2.006118,0.0
std,2.207969,22132.758713,65.560570,17.644635,0.574467,21.142188,1.472310,0.0
min,1991.000000,-58540.574478,-91.121630,-43.421768,-0.103493,1.638913,-2.345650,0.0
25%,2016.000000,7298.250000,125.000000,46.300000,1.200000,47.000000,1.000000,0.0
50%,2017.000000,17225.500000,145.000000,54.300000,1.600000,65.000000,2.000000,0.0
75%,2019.000000,32500.000000,145.000000,62.800000,2.000000,82.000000,3.000000,0.0
max,2024.121759,279000.000000,580.000000,470.800000,6.600000,125.594308,6.258371,0.0

From the numeric describe we can see that we have some weird values:

    1. negative mileage, tax, mpg, engineSize, previousOwners in the minimum value
    2. hasDamage is a boolean but we can see that instead of 0 and 1 we only have 0 and Nones*
    3. previousOwner has a float? Should we round it?

*check in the hasDamage column

What will we do:

    1. Count the number of negative values and decide if we should drop or change them.
    2. Replace the nones by 1's. (data-preparation)
    3. Count the number of float values and decide to drop or round them.

In [ ]:
test.describe(include='object')

        Brand   model transmission fuelType
count   31918   31917        31944    31911
unique     64     593           38       29
top      Ford   Focus       Manual   Petrol
freq     6360    2721        16312    16113

From the categorical describe we tell that:

    - This columns also have missing values
    - transmission has 38 unique values and fuelType has 29...

In [ ]:
train.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

# Data Preprocessing

What should we do with the negative values? First of all we'll analyse them.

In [ ]:
mileage_train_negatives = train['mileage']<0
tax_train_negatives = train['tax']<0
mpg_train_negatives = train['mpg']<0
engineSize_train_negatives = train['engineSize']<0
previousOwners_train_negatives = train['previousOwners']<0


#here we used chatGPT to help us to construct the following DataFrame
negatives_summary = pd.DataFrame({
    'mileage_negatives': mileage_train_negatives.value_counts(),
    'tax_negatives': tax_train_negatives.value_counts(),
    'mpg_negatives': mpg_train_negatives.value_counts(),
    'engineSize_negatives': engineSize_train_negatives.value_counts(),
    'previousOwners_negatives': previousOwners_train_negatives.value_counts()
})

negatives_summary

In [ ]:
#Check the percentage of negative mileage values
data_len = len(train['mileage'])

#Here we used chatGPT to help us constructing the final negatives_table
negatives_percent = {
    'mileage_negatives (%)': mileage_train_negatives.sum() / data_len * 100,
    'tax_negatives (%)': tax_train_negatives.sum() / data_len * 100,
    'mpg_negatives (%)': mpg_train_negatives.sum() / data_len * 100,
    'engineSize_negatives (%)': engineSize_train_negatives.sum() / data_len * 100,
    'previousOwners_negatives (%)': previousOwners_train_negatives.sum() / data_len * 100
}

# Converter para DataFrame (tabela)
negatives_table = pd.DataFrame(negatives_percent, index=['Percentage of Negatives']).round(3)

negatives_table

From the negatives_table we obtain very low percentages for each variable, lower than 1%. So it's possible to conclude that this values are a small part of our data and that if we drop them we don't loose veracity.

We can also see that the total percentage of negative values is lower then 5%.

In [ ]:
# The goal is to count the values that are floats, this is, the values that have decimals different than 0
# To do this we create a variable with only the values that have decimals cases different than 0, that is, 
#the values for which the remainder of the division by 1 is not 0
has_decimals = train['previousOwners'] % 1 != 0
print(has_decimals.sum())
#at the end we sum all those values to find how many "real" floats exist


has_decimals.sum() / data_len * 100

In [ ]:
brand_same_size = train['Brand'].str.lower()
brand_same_size.value_counts().to_frame()

In [ ]:
mapping_brands = {
    'ord' : 'ford',
    'for' : 'ford',
    'ercedes' : 'mercedes',
    'mercede' : 'mercedes',
    'w' : 'vw',
    'v' : 'vw',
    'ope' : 'opel',
    'pel' : 'opel',
    'mw' : 'bmw',
    'aud' : 'audi',
    'udi' : 'audi',
    'bm' : 'bmw',
    'oyota' : 'toyota',
    'koda' : 'skoda',
    'skod' : 'skoda',
    'toyot' : 'toyota',
    'yundai' : 'hyundai',
    'hyunda' : 'hyundai',
    'ercede' : 'mercedes',
    'or' : 'ford',
    'pe' : 'opel',
    'yunda' : 'hyundai',
    'ud' : 'audi',
    'kod' : 'skoda'
}
#train['Brand'] = train['Brand].replace(mapping_brands)

podemos usar esta maneira ou uma biblioteca chamada fuzzy matching mas não sei se vai ser permitido

hasDamage column - replace None values by 1

In [ ]:
train['hasDamage']=train['hasDamage'].fillna(1) #do the same for test set?

In [ ]:
#validate the changes, isto podemos apagar depois
train['hasDamage'].value_counts()

previousOwner column - round to transform float into int

In [ ]:
train['previousOwners'] = train['previousOwners'].round(0) #do the same for test set?

In [ ]:
train['previousOwners'].value_counts() #negative values remove or stay? isto podemos apagar depois